### ISSUE TITLE
Asiakas pystyy lisäämään Inproceedings tyyppisen viitteen

### ISSUE THREAD

**Issue by mcpaulafi** [Eeritvan/ohtu-tiistai#1]
Käyttäjänä voin lisätä in proceedings -lähteen web appiin.

| Kuvaus              | Vastuuhenkilö | Status | 12.11 | 13.11 | 14.11 | 15.11 | 16.11 | 17.11 | 18.11 | 19.11 |
| :---------------- | :------: | ----------: | :---------: | :------: | :------: | :------: | :------:  | :------:  | :------:  | :------: |
| UI ja python koodin tekstien muuttaminen Todo->Ref        |   Paula    | Done | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| UI lomake Inproceedings kenttien lisäys + validointia           |   Paula  | Done | 3 | 3 | 3 | 3 | 0 | 0 | 0 | 0 |
| Tietokantataulun nimeäminen ja Inproceedigs kentien lisäys    |  JUKKA  | Done | 3 | 3 | 2 | 0 | 0 | 0 | 0 | 0 |
| Integraatio HTML syöte -> SQL eli olio    |  Margit, Eetu  | Done  | 4 | 4 |4 | 4 |3 | 1 | 0 | 0 | ?
| Syötteiden validointi    | Paula  | Done | 2 | 2 | 0 | 0 | 0 | 0 | 0 | 0 |
| Robots-testi uusitulle lomakkeelle |  Eetu  | Done | 4 | 4 | 4 | 4 | 4 | 4 | 0 | 0 |
| Unit-testit |  Eetu | Done | 2 | 2 | 2 | 2 | 2 | 2 | 0 | 0 |
| Pylint testit koodille |  Eetu  | Done | 2 | 2 | 0 | 0 | 0 | 0 | 0 | 0 |
| Github actions workflow |  Eetu  | Done | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 |
| db_helper.py-tiedoston päivitys    |  JUKKA  | Done | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 0 |

Status-vaihtoehdot: Not started, In-progress, Testing, Done

**Hyväksymiskriteerit**
-

**Comment by mcpaulafi** [comment]
Inproceedings-tyypin tekninen kuvaus https://bibtex.eu/types/inproceedings/

**Comment by jkuusto** [comment]
Tietokantaskeeman tuonti omaan tietokantaan:
psql -U psql_username -d database_name -f schema.sql

Tämä tuo vain uuden taulun "sources". Se ei poista boilerplate-projektin "todo"-taulua. Sen voi halutessaan poistaa itse, kun kokee, ettei sitä enää tarvitse.
